name: 'Deploy continious'
description: 'Deploy continious build'
inputs:
  rid:
    description: 'Runtime identifier'
    required: true
    type: string
  gh-token:
    description: 'GitHub token'
    required: true
    type: string
  nuget-token:
    description: 'Nuget API key'
    required: true
    type: string
  publish-path:
    description: 'Path to published artifacts'
    required: true
    type: string
    
runs:
  using: "composite"
  steps:
    - id: push-nuget-nupkg
      run: |
        foreach($file in (Get-ChildItem "${{ inputs.publish-path }}/" -Recurse -Include *.nupkg))
        {
            dotnet --info
            echo dotnet nuget push $file.FullName --source "https://api.nuget.org/v3/index.json" --skip-duplicate
            dotnet nuget push $file.FullName -k ${{ inputs.nuget-token }} -s "https://api.nuget.org/v3/index.json" -ss "https://api.nuget.org/v3/index.json" --skip-duplicate
        }
      shell: pwsh
    - id: push-github-nupkg
      run: echo "Placeholder"
      shell: pwsh
    - id: push-github-docker
      run: echo "Placeholder"
      shell: pwsh
    - id: create-release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: continious
        files: ${{ inputs.publish-path }}/${{ inputs.rid }}.zip
        name: Continuous build
        token: ${{ inputs.gh-token }}
        prerelease: true
      
