name: 'Read version'
description: 'Reads version prefix and suffix'
outputs:
  prefix:
    description: 'Version prefix'
    value: ${{ steps.version.outputs.prefix }}
  suffix:
    description: 'Version suffix'
    value: ${{ steps.version.outputs.suffix }}
        
runs:
  using: "composite"
  defaults:
    run:
      shell: pwsh
  steps:
    - id: version
      run: |
        $Path = "Directory.Build.props"
        $XPath = "/Project/PropertyGroup/VersionPrefix"
        $versionPrefix = (Select-Xml -Path $Path -XPath $Xpath).Node.InnerText
        echo "prefix=$versionPrefix" >> $env:GITHUB_OUTPUT
        $XPath = "/Project/PropertyGroup/VersionSuffix"
        $versionSuffix = (Select-Xml -Path $Path -XPath $Xpath).Node.InnerText
        echo "suffix=$versionSuffix" >> $env:GITHUB_OUTPUT
