name: 'Read version'
description: 'Reads version prefix and suffix'
outputs:
  prefix:
    description: 'Version prefix'
    value: ${{steps.version.outputs.prefix}}
  suffix:
    description: 'Version suffix'
    value: ${{steps.version.outputs.suffix}}
  build:
    description: 'Build number, taken from AssemblyVersion'
    value: ${{steps.version.outputs.build}}
  docker-tag:
    description: 'Latest for ci, vprefix for release'
    value: ${{steps.version.outputs.docker-tag}}
        
runs:
  using: "composite"
  steps:
    - id: version
      run: |
        $Path = "Directory.Build.props"
        Set-Variable VersionPrefixPath -Option ReadOnly -Value "/Project/PropertyGroup/VersionPrefix"
        Set-Variable VersionSuffixPath -Option ReadOnly -Value "/Project/PropertyGroup/VersionSuffix"
        Set-Variable AssemblyVersionPath -Option ReadOnly -Value "/Project/PropertyGroup/AssemblyVersion"

        $versionPrefix = (Select-Xml -Path $path -XPath $VersionPrefixPath).Node.InnerText
        $versionSuffix = (Select-Xml -Path $path -XPath $VersionSuffixPath).Node.InnerText
        $assemblyVersion = (Select-Xml -Path $path -XPath $AssemblyVersionPath).Node.InnerText
        $buildVersion = $assemblyVersion.Split('.')[-1]
        $dockerTag = ""

        if ("$versionSuffix") {
            $dockerTag = "latest"
        }
        else {
            $dockerTag = "v$versionPrefix"
        }

        Write-Output "prefix=$versionPrefix" >> $env:GITHUB_OUTPUT
        Write-Output "suffix=$versionSuffix" >> $env:GITHUB_OUTPUT
        Write-Output "build=$buildVersion" >> $env:GITHUB_OUTPUT
        Write-Output "docker-tag=$dockerTag" >> $env:GITHUB_OUTPUT

      shell: pwsh
