name: 'Deploy release'
description: 'Deploy release'
inputs:
  rid:
    description: 'Runtime identifier'
    required: true
    type: string
  version:
    description: 'Release version'
    required: true
    type: string
  gh-token:
    description: 'GitHub token'
    required: true
    type: string
  publish-path:
    description: 'Path to published artifacts'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - id: push-github-docker
      run: echo "Placeholder"
      shell: pwsh
    - id: generate-changelog
      run: echo "# Release details" > ${{github.workspace}}-CHANGELOG.txt
      shell: pwsh
    - id: create-release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{inputs.version}}
        generate_release_notes: true
#         body_path: ${{github.workspace}}-CHANGELOG.txt
        files: ${{inputs.publish-path}}/${{inputs.rid}}.zip
        token: ${{inputs.gh-token}}
      
