name: build-test-deploy

on: [push, pull_request]

jobs:

# no point in matrix without deploy tasks
# see discussion: https://github.com/orgs/community/discussions/42335

#   build-test:
#     strategy:
#       matrix:
#         os: [ubuntu-latest, windows-latest, macos-latest]
#     uses: ./.github/workflows/build-test.yml
#     with:
#       runs-on:  ${{ matrix.os }}

# passing env to jobs
# see: https://github.com/orgs/community/discussions/26671

# building and testing tasks

  build-test-windows:
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: windows-latest
      dotnet-version: '7.x'
    secrets: inherit
  build-test-linux:
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: ubuntu-latest
      dotnet-version: '7.x'
    secrets: inherit
  build-test-macos:
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: macos-latest
      dotnet-version: '7.x'
    secrets: inherit
      
# deploy binaries

  deploy-binaries-windows:
    needs: build-test-windows
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deploy-binaries.yml
    concurrency:
      group: "deploy-binaries-windows"
      cancel-in-progress: false
    with:
      runs-on: windows-latest
      projects: '["Deploy.Cli/Deploy.Cli.csproj"]'
      publish-base: 'publish'
      continious-tag: 'continious'
      dotnet-version: '7.x'
      build-props-path: 'Directory.Build.props'
    secrets: inherit
    
  deploy-binaries-linux:
    needs: build-test-linux
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deploy-binaries.yml
    concurrency:
      group: "deploy-binaries-linux"
      cancel-in-progress: false
    with:
      runs-on: ubuntu-latest
      projects: '["Deploy.Cli/Deploy.Cli.csproj"]'
      publish-base: 'publish'
      continious-tag: 'continious'
      dotnet-version: '7.x'
      build-props-path: 'Directory.Build.props'
    secrets: inherit
    
  deploy-binaries-macos:
    needs: build-test-macos
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deploy-binaries.yml
    concurrency:
      group: "deploy-binaries-macos"
      cancel-in-progress: false
    with:
      runs-on: macos-latest
      projects: '["Deploy.Cli/Deploy.Cli.csproj"]'
      publish-base: 'publish'
      continious-tag: 'continious'
      dotnet-version: '7.x'
      build-props-path: 'Directory.Build.props'
    secrets: inherit
    
# deploy pages

  deploy-pages-linux:
    needs: build-test-linux
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deploy-pages.yml
    concurrency:
      group: "deploy-pages"
      cancel-in-progress: false
    with:
      runs-on: ubuntu-latest
      publish-base: 'publish'
      continious-tag: 'continious'
      build-props-path: 'Directory.Build.props'
    secrets: inherit
    
# deploy src

  deploy-src-linux:
    needs: build-test-linux
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deploy-src.yml
    concurrency:
      group: "deploy-src-linux"
      cancel-in-progress: false
    with:
      runs-on: ubuntu-latest
      dotnet-version: '7.x'
      docfx-json-path: 'docfx.json'
      publish-dir: 'docs'
    secrets: inherit
    
# deploy peckages
    
  deploy-packages-nuget-linux:
    needs: build-test-linux
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deploy-packages.yml
    concurrency:
      group: "deploy-packages-nuget-linux"
      cancel-in-progress: false
    with:
      runs-on: ubuntu-latest
      packages: '["Deploy.Core/Deploy.Core.csproj"]'
      publish-base: 'publish'
      package-feed: "https://api.nuget.org/v3/index.json"
      dotnet-version: '7.x'
      build-props-path: 'Directory.Build.props'
    secrets: 
      TOKEN: ${{secrets.NUGET_API_KEY}}
      
  deploy-packages-github-linux:
    needs: build-test-linux
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deploy-packages.yml
    concurrency:
      group: "deploy-packages-github-linux"
      cancel-in-progress: false
    with:
      runs-on: ubuntu-latest
      packages: '["Deploy.Core/Deploy.Core.csproj"]'
      publish-base: 'publish'
      package-feed: "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json"
      dotnet-version: '7.x'
      build-props-path: 'Directory.Build.props'
    secrets: 
      TOKEN: ${{secrets.GITHUB_TOKEN}}
    
# deploy docker

  deploy-docker-docker-hub-linux:
    needs: build-test-linux
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        project: ["deploy.cli---Dockerfile"]
    uses: ./.github/workflows/deploy-docker.yml
    concurrency:
      group: "deploy-docker-docker-hub-linux"
      cancel-in-progress: false
    with:
      runs-on: ubuntu-latest
      registry: 'docker.io'
      project: ${{matrix.project}}
      build-props-path: 'Directory.Build.props'
      continious-tag: 'latest'
    secrets:
      USERNAME: ${{secrets.DOCKER_USERNAME}}
      TOKEN: ${{secrets.DOCKER_PASSWORD}}
    
  deploy-docker-github-linux:
    needs: build-test-linux
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        project: ["deploy.cli---Dockerfile"]
    uses: ./.github/workflows/deploy-docker.yml
    concurrency:
      group: "deploy-docker-github-linux"
      cancel-in-progress: false
    with:
      runs-on: ubuntu-latest
      registry: 'ghcr.io'
      project: ${{matrix.project}}
      build-props-path: 'Directory.Build.props'
      continious-tag: 'latest'
    secrets:
      USERNAME: ${{github.repository_owner}}
      TOKEN: ${{secrets.GITHUB_TOKEN}}
    
    
