name: build-test-deploy

on: [push, pull_request]

jobs:

# building and testing tasks

  build-test-windows:
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: windows-latest
  build-test-linux:
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: ubuntu-latest
  build-test-macos:
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: macos-latest
      
# publishing tasks
      
  deploy-windows:
    needs: build-test-windows
    if: github.event_name == 'push'
    uses: ./.github/workflows/deploy.yml
    with:
      runs-on: windows-latest
      rid: "win-x64"
      publish-path: 'publish'
      gh-nuget-source: 'senketsu03'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  deploy-linux:
    needs: build-test-linux
    if: github.event_name == 'push'
    uses: ./.github/workflows/deploy.yml
    with:
      runs-on: ubuntu-latest
      rid: "linux-x64"
      publish-path: 'publish'
      gh-nuget-source: 'senketsu03'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  deploy-macos:
    needs: build-test-macos
    if: github.event_name == 'push'
    uses: ./.github/workflows/deploy.yml
    with:
      runs-on: macos-latest
      rid: "osx-x64"
      publish-path: 'publish'
      gh-nuget-source: 'senketsu03'
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
