name: build-and-test

on: [push, pull_request]

jobs:
  build-test-windows:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      runs-on: windows-latest
  build-test-linux:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      runs-on: ubuntu-latest
  build-test-macos:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      runs-on: macos-latest
      
  publish-linux-cli:
    runs-on: ubuntu-latest
    env:
      rid: "linux-x64"
    needs: build-test-linux
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - name: Publish
        run: dotnet publish "Deploy.Cli/Deploy.Cli.csproj" -c Release -r $rid -o "publish/$rid" --sc false
      - name: Zip
        run: zip -r $rid.zip publish/$rid
      - name: Generate Changelog
        run: echo "# Release details" > ${{ github.workspace }}-CHANGELOG.txt
      - name: Create and upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: continious
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: ./linux-x64.zip
          name: Continuous build
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
