name: build-test-deploy

on: [push, pull_request]

env:
  DUMMY: 'karasique'

jobs:

# building and testing tasks

# no point in matrix without deploy tasks
# see discussion: https://github.com/orgs/community/discussions/42335

#   build-test:
#     strategy:
#       matrix:
#         os: [ubuntu-latest, windows-latest, macos-latest]
#     uses: ./.github/workflows/build-test.yml
#     with:
#       runs-on:  ${{ matrix.os }}

  build-test-windows:
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: windows-latest
  build-test-linux:
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: ubuntu-latest
  build-test-macos:
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: macos-latest
      
# publishing tasks
      
  deploy-windows:
    needs: build-test-windows
    if: github.event_name == 'push'
    uses: ./.github/workflows/deploy.yml
    with:
      runs-on: windows-latest
      publish-path: 'publish'
      gh-nuget-source: 'senketsu03'
      dummy: ${{env.DUMMY}}
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  deploy-linux:
    needs: build-test-linux
    if: github.event_name == 'push'
    uses: ./.github/workflows/deploy.yml
    with:
      runs-on: ubuntu-latest
      publish-path: 'publish'
      gh-nuget-source: 'senketsu03'
      dummy: ${{env.DUMMY}}
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  deploy-macos:
    needs: build-test-macos
    if: github.event_name == 'push'
    uses: ./.github/workflows/deploy.yml
    with:
      runs-on: macos-latest
      publish-path: 'publish'
      gh-nuget-source: 'senketsu03'
      dummy: ${{env.DUMMY}}
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
