name: build-test
on:
  workflow_call:
    inputs:
      runs-on:
        description: 'The operating system to run the job on'
        required: true
        type: string
jobs:
  build-test:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - name: dotnet-setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - name: dotnet-restore
        run: dotnet restore
      - name: dotnet-build
        run: dotnet build --no-restore -c Release
      - name: dotnet-test
        run: dotnet test --no-restore -c Release
