name: build-test-deploy

on: [push, pull_request]

jobs:

# building and testing tasks

  build-test-windows:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      runs-on: windows-latest
  build-test-linux:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      runs-on: ubuntu-latest
  build-test-macos:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      runs-on: macos-latest
      
# publishing tasks
      
  publish-windows-cli:
    needs: build-test-windows
    uses: ./.github/workflows/reusable-cli-deploy.yml
    with:
      runs-on: windows-latest
      rid: "win-x64"
  publish-linux-cli:
    needs: build-test-linux
    uses: ./.github/workflows/reusable-cli-deploy.yml
    with:
      runs-on: ubuntu-latest
      rid: "linux-x64"
  publish-macos-cli:
    needs: build-test-macos
    uses: ./.github/workflows/reusable-cli-deploy.yml
    with:
      runs-on: macos-latest
      rid: "osx-x64"

# experimental deploy depending on props version info

#   read-version:
#     defaults:
#       run:
#         shell: pwsh
#     runs-on: ubuntu-latest
#     outputs:
#       suffix: ${{ steps.version.outputs.suffix }}
#       prefix: ${{ steps.version.outputs.prefix }}
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Read Version
#         id: version
#         run: |
#           $Path = "Directory.Build.props"
#           $XPath = "/Project/PropertyGroup/VersionSuffix"
#           $versionSuffix = (Select-Xml -Path $Path -XPath $Xpath).Node.InnerText
#           echo "suffix=$versionSuffix" >> $env:GITHUB_OUTPUT
#           $XPath = "/Project/PropertyGroup/VersionPrefix"
#           $versionPrefix = (Select-Xml -Path $Path -XPath $Xpath).Node.InnerText
#           echo "prefix=$versionPrefix" >> $env:GITHUB_OUTPUT

  read-version:
    uses: ./.github/workflows/reusable-read-version.yml
    with:
      runs-on: ubuntu-latest

  deploy-release:
    needs: read-version
    if: needs.read-version.outputs.suffix == ''
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Release
        run: echo "Deploying release version ${{ needs.read-version.outputs.prefix }}"

  deploy-continious:
    needs: read-version
    if: needs.read-version.outputs.suffix != ''
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Continious
        run: echo "Deploying continious version ${{ needs.read-version.outputs.prefix }}-${{ needs.read-version.outputs.suffix }}"



