name: build-and-test

on: [push, pull_request]

jobs:
  build-test-windows:
    uses: ./.github/workflows/reusable-build-test.yml
  build-test-linux:
    uses: ./.github/workflows/reusable-build-test.yml
