name: build-and-test

on: [push, pull_request]

jobs:

  build-windows:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Cache build output
      uses: actions/cache@v2
      with:
        path: .
        key: $ { { runner.os }}-repo-${ { github.sha }}
        restore-keys: |
          $ { { runner.os }}-repo-
          
  test-windows:
  
    runs-on: windows-latest
    needs: build-windows
    steps:
    - name: Restore repo
      uses: actions/cache@v2
      with:
        path: .
        key: $ { { runner.os }}-repo-${ { github.sha }}
        restore-keys: |
          $ { { runner.os }}-repo-
    - name: Test
      run: dotnet test --no-restore -c Release
