name: build-test-deploy

on: [push, pull_request]

jobs:

# building and testing tasks

# no point in matrix without deploy tasks
# see discussion: https://github.com/orgs/community/discussions/42335

#   build-test:
#     strategy:
#       matrix:
#         os: [ubuntu-latest, windows-latest, macos-latest]
#     uses: ./.github/workflows/build-test.yml
#     with:
#       runs-on:  ${{ matrix.os }}

# passing env to jobs
# see: https://github.com/orgs/community/discussions/26671

  build-test-windows:
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: windows-latest
    secrets: inherit
  build-test-linux:
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: ubuntu-latest
    secrets: inherit
  build-test-macos:
    uses: ./.github/workflows/build-test.yml
    with:
      runs-on: macos-latest
    secrets: inherit
      
# deploy binaries
      
  deploy-binaries-windows:
    needs: build-test-windows
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deploy-binaries.yml
    with:
      runs-on: windows-latest
      publish-base: 'publish'
    secrets: inherit
  deploy-binaries-linux:
    needs: build-test-linux
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deploy-binaries.yml
    with:
      runs-on: ubuntu-latest
      publish-base: 'publish'
    secrets: inherit
  deploy-binaries-macos:
    needs: build-test-macos
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deploy-binaries.yml
    with:
      runs-on: macos-latest
      publish-base: 'publish'
    secrets: inherit
    
# deploy peckages

#   deploy-packages-linux:
#     needs: build-test-linux
#     if: github.ref == 'refs/heads/master'
#     uses: ./.github/workflows/deploy-packages.yml
#     with:
#       runs-on: ubuntu-latest
#       publish-base: 'publish'
#       gh-nuget-source: ${{github.repository_owner}}
#     secrets: inherit
    
  deploy-packages-nuget-linux:
    needs: build-test-linux
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deploy-packages-new.yml
    with:
      runs-on: ubuntu-latest
      packages: '["Deploy.Core/Deploy.Core.csproj"]'
      publish-base: 'publish'
      package-feed: "https://api.nuget.org/v3/index.json"
    secrets: 
      TOKEN: ${{secrets.NUGET_API_KEY}}
      
  deploy-packages-github-linux:
    needs: build-test-linux
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deploy-packages-new.yml
    with:
      runs-on: ubuntu-latest
      packages: '["Deploy.Core/Deploy.Core.csproj"]'
      publish-base: 'publish'
      package-feed: "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json"
    secrets: 
      TOKEN: ${{secrets.GITHUB_TOKEN}}
    
# deploy docker

  deploy-docker-linux-docker-hub:
    needs: build-test-linux
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        project: ["deploy.cli---Dockerfile"]
    uses: ./.github/workflows/deploy-docker.yml
    with:
      runs-on: ubuntu-latest
      registry: 'docker.io'
      project: ${{matrix.project}}
    secrets:
      USERNAME: ${{secrets.DOCKER_USERNAME}}
      TOKEN: ${{secrets.DOCKER_PASSWORD}}
    
  deploy-docker-linux-github:
    needs: build-test-linux
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        project: ["deploy.cli---Dockerfile"]
    uses: ./.github/workflows/deploy-docker.yml
    with:
      runs-on: ubuntu-latest
      registry: 'ghcr.io'
      project: ${{matrix.project}}
    secrets:
      USERNAME: ${{github.repository_owner}}
      TOKEN: ${{secrets.GITHUB_TOKEN}}
    
    
