name: deploy-docker
on:
  workflow_call:
    inputs:
      runs-on:
        description: 'The operating system to run the job on'
        required: true
        type: string
    secrets:
      NUGET_API_KEY:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
        
jobs:
  deploy-docker-hub:
    runs-on: ${{inputs.runs-on}}
    defaults:
      run:
        shell: pwsh
    env:
      version: ''
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: read-version
        id: read-version
        uses: ./.github/actions/read-version
        
      - name: set-version
        run: |
          if ('${{steps.read-version.outputs.suffix}}')
          {
              echo 'version=latest' >> $env:GITHUB_ENV
          }
          else
          {
              echo 'version=v${{steps.read-version.outputs.prefix}}' >> $env:GITHUB_ENV
          }
      - name: echo-version
        run: echo 'version == ${{env.version}}'

      - name: docker-hub-login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          
      - name: docker-extract-meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{secrets.DOCKER_USERNAME}}/deploy.cli
          tags: type=raw,value=${{env.version}}
          
      - name: Echo meta
        run: |
          echo Meta == ${{steps.meta}}
          echo Meta.output == ${{steps.meta.outputs}}
          
#       - name: Build and push Docker image
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           file: ./Dockerfile
#           push: ${{github.event_name != 'pull_request'}}
#           tags: ${{steps.meta.outputs.tags}}
#           labels: ${{steps.meta.outputs.labels}}
          
# Doesnt work, see: https://github.com/peter-evans/dockerhub-description/issues/10
#       - name: Update Docker Hub Description
#         uses: peter-evans/dockerhub-description@v3
#         with:
#           username: ${{secrets.DOCKER_USERNAME}}
#           password: ${{secrets.DOCKER_PASSWORD}}

  deploy-docker-github:
    runs-on: ${{inputs.runs-on}}
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: read-version
        id: read-version
        uses: ./.github/actions/read-version
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
          
      - name: Extract docker image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{github.repository_owner}}/${{github.repository}}/deploy.cli
                    
      - name: Echo meta
        run: |
          echo Meta == ${{steps.meta}}
          echo Meta.output == ${{steps.meta.outputs}}
          
#       - name: Manual build and push Docker image
#         run: |
#           docker build -t ${{steps.meta.outputs.tags}} -f Dockerfile .
#           docker push ${{steps.meta.outputs.tags}}
          
#       - name: Build and push Docker image
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           file: ./Dockerfile
#           push: ${{github.event_name != 'pull_request'}}
#           tags: ${{steps.meta.outputs.tags}}
#           labels: ${{steps.meta.outputs.labels}}
        
