name: deploy
on:
  workflow_call:
    inputs:
      runs-on:
        description: 'The operating system to run the job on'
        required: true
        type: string
      rid:
        description: 'Runtime identifier'
        required: true
        type: string
        
jobs:
  deploy:
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v3
      - name: read-version
        id: read-version
        uses: ./.github/actions/read-version
      - name: dotnet-setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
          
      - name: dotnet-build
        run: dotnet build -c Release -r "${{ inputs.rid }}"
          
      - name: dotnet-publish
        run: dotnet publish "Deploy.Cli/Deploy.Cli.csproj" -c Release -r "${{ inputs.rid }}" -o "publish/${{ inputs.rid }}" --sc false --no-build
      - name: zip-artifacts
        run: Compress-Archive -Path publish/${{ inputs.rid }}/* -Destination ${{ inputs.rid }}.zip
        
        # pack core TODO move
      - name: dotnet-pack
        run: dotnet pack "Deploy.Core/Deploy.Core.csproj" -c Release -o "publish/Deploy.Core" --no-build

      - name: deploy-release
        if: steps.read-version.outputs.suffix == ''
        uses: ./.github/actions/deploy-release
        with:
          rid: ${{ inputs.rid }}
          version: ${{ steps.read-version.outputs.prefix }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: deploy-continious
        if: steps.read-version.outputs.suffix != ''
        uses: ./.github/actions/deploy-continious
        with:
          rid: ${{ inputs.rid }}
          token: ${{ secrets.GITHUB_TOKEN }}
        
