name: deploy
on:
  workflow_call:
    inputs:
      runs-on:
        description: 'The operating system to run the job on'
        required: true
        type: string
      rid:
        description: 'Runtime identifier'
        required: true
        type: string
      publish-path:
        description: 'Base path to publish artifact'
        required: true
        type: string
        
env:
  DUMMY: ${{ secrets.DUMMY }}
        
jobs:
  deploy:
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v3
      - name: read-version
        id: read-version
        uses: ./.github/actions/read-version
      - name: dotnet-setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
          
      - name: dotnet-publish
        run: dotnet publish "Deploy.Cli/Deploy.Cli.csproj" -c Release -r "${{ inputs.rid }}" -o "${{ inputs.publish-path }}/${{ inputs.rid }}" --sc false
      - name: zip-artifacts
        run: Compress-Archive -Path ${{ inputs.publish-path }}/${{ inputs.rid }}/* -Destination ${{ inputs.publish-path }}/${{ inputs.rid }}.zip
        
      - name: dotnet-build
        run: dotnet build -c Release
        
      - name: dotnet-pack-release
        if: steps.read-version.outputs.suffix == ''
        run: dotnet pack "Deploy.Core/Deploy.Core.csproj" -c Release -o "${{ inputs.publish-path }}/Nupkg" --no-build
      - name: dotnet-pack-continious
        if: steps.read-version.outputs.suffix != ''
        run: dotnet pack "Deploy.Core/Deploy.Core.csproj" -c Release -o "${{ inputs.publish-path }}/Nupkg" --no-build --version-suffix ci-${{ steps.read-version.outputs.build }}

      - name: echo env
        run: |
          echo Dummy: $DUMMY
          echo Dummy_env: ${{ env.DUMMY }}
          echo Dummy_secret: ${{ secrets.DUMMY }}

      - name: deploy-release
        if: steps.read-version.outputs.suffix == ''
        uses: ./.github/actions/deploy-release
        with:
          rid: ${{ inputs.rid }}
          version: ${{ steps.read-version.outputs.prefix }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: deploy-continious
        if: steps.read-version.outputs.suffix != ''
        uses: ./.github/actions/deploy-continious
        with:
          rid: ${{ inputs.rid }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          nuget-token: ${{ secrets.NUGET_API_KEY }}
          dummy: ${{ env.DUMMY }}
          publish-path: ${{ inputs.publish-path }}
        
