name: reusable-read-version
on:
  workflow_call:
    inputs:
      runs-on:
        description: 'The operating system to run the job on'
        required: true
        type: string
jobs:
  read-version:
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        shell: pwsh
    outputs:
      suffix: ${{ steps.version.outputs.suffix }}
      prefix: ${{ steps.version.outputs.prefix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read Version
        id: version
        run: |
          $Path = "Directory.Build.props"
          $XPath = "/Project/PropertyGroup/VersionSuffix"
          $versionSuffix = (Select-Xml -Path $Path -XPath $Xpath).Node.InnerText
          echo "suffix=$versionSuffix" >> $env:GITHUB_OUTPUT
          $XPath = "/Project/PropertyGroup/VersionPrefix"
          $versionPrefix = (Select-Xml -Path $Path -XPath $Xpath).Node.InnerText
          echo "prefix=$versionPrefix" >> $env:GITHUB_OUTPUT
